export const CONSTANT = {
  COMPANY_FIELD: [
    {CODE: 'RETAIL_WHOLESALE', NAME: 'Bán lẻ/Bán sỉ'},
    {CODE: 'PACKAGING_PRINTING_STICKERS', NAME: 'Bao bì/In ấn/Nhãn dán',},
    {CODE: 'INSURANCE', NAME: 'Bảo hiểm'},
    {CODE: 'REAL_ESTATE_LEASE', NAME: 'Bất động sản/Cho thuê',},
    {CODE: 'GOVERNMENT_NGO', NAME: 'Chính phủ & NGO'},
    {CODE: 'STOCK', NAME: 'Chứng khoán'},
    {CODE: 'SUPPLY_CHAIN', NAME: 'Chuỗi cung ứng'},
    {CODE: 'MECHANICAL_MACHINES_INDUSTRIAL_EQUIPMENT', NAME: 'Cơ khí/Máy móc/Thiết bị công nghiệp',},
    {CODE: 'SUPPLY_MANPOWER', NAME: 'Cung cấp nhân lực'},
    {CODE: 'TEXTILE_GARMENT_FOOTWEAR', NAME: 'Dệt may/May mặc/Giày dép',},
    {CODE: 'WAREHOUSING_SERVICES', NAME: 'Dịch vụ kho bãi',},
    {CODE: 'LODGING_RESTAURANT_HOTEL_TOURISM', NAME: 'Dịch vụ lưu trú/Nhà hàng/Du lịch',},
    {CODE: 'ENVIRONMENTAL_SERVICES_WASTE', NAME: 'Dịch vụ môi trường/Chất thải',},
    {CODE: 'MEDICAL_SERVICES_HEALTH_CARE', NAME: 'Dịch vụ y tế/Chăm sóc sức khỏe',},
    {CODE: 'ELECTRICAL_ELECTRONIC', NAME: 'Điện/Điện tử',},
    {CODE: 'PHARMACEUTICAL', NAME: 'Dược phẩm'},
    {CODE: 'EDUCATION_TRAINING', NAME: 'Giáo dục/Đào tạo',},
    {CODE: 'CONSUMER_GOODS', NAME: 'Hàng tiêu dùng'},
    {CODE: 'LOGISTICS_TRANSPORTATION', NAME: 'Hậu cần/Giao nhận',},
    {CODE: 'INFORMATION_TECHNOLOGY_SYSTEMS_EQUIPMENT', NAME: 'Hệ thống CNTT/Thiết bị',},
    {CODE: 'CHEMICAL_BIOCHEMISTRY', NAME: 'Hóa chất/Hóa sinh',},
    {CODE: 'ACCOUNTING_AUDIT', NAME: 'Kế toán/Kiểm toán'},
    {CODE: 'MINING_OIL_AND_GAS', NAME: 'Khai khoáng/Dầu khí',},
    {CODE: 'ARCHITECTURE_INTERIOR', NAME: 'Kiến trúc nội thất',},
    {CODE: 'CONSTRUCTION_ENGINEERING_INFRASTRUCTURE', NAME: 'Ký sư xây dựng/Cơ sở hạ tầng',},
    {CODE: 'BEAUTY_PERSONAL_CARE', NAME: 'Làm đẹp/Chăm sóc cá nhân',},
    {CODE: 'LAW_LEGAL_SERVICES', NAME: 'Luật/Dịch vụ pháp lý',},
    {CODE: 'BANKING', NAME: 'Ngân hàng'},
    {CODE: 'ART_ENTERTAINMENT', NAME: 'Nghệ thuật/Giải trí',},
    {CODE: 'RESEARCH', NAME: 'Nghiên cứu'},
    {CODE: 'IMPORT_EXPORT', NAME: 'Nhập khẩu/Xuất khẩu'},
    {CODE: 'PLASTIC_RUBBER', NAME: 'Nhựa/Cao su'},
    {CODE: 'WOODEN_FURNITURE', NAME: 'Nội thất/Gỗ'},
    {CODE: 'AGRICULTURE_FORESTRY_AQUACULTURE', NAME: 'Nông nghiệp/Lâm nghiệp/Nuôi trồng thủy sản',},
    {CODE: 'AUTOMOBILE', NAME: 'Ô tô'},
    {CODE: 'INFORMATION_TECHNOLOGY_SOFTWARE_SOFTWARE_SERVICES', NAME: 'Phần mềm CNTT/ Dịch vụ phần mềm',},
    {CODE: 'PRODUCTION', NAME: 'Sản xuất'},
    {CODE: 'PRODUCTION_AND_DISTRIBUTION_OF_ELECTRICITY_GAS_WATER', NAME: 'Sản xuất và phân phối điện/Khí đốt/Nước',},
    {CODE: 'FINANCE', NAME: 'Tài chính'},
    {CODE: 'MEDICAL_EQUIPMENT', NAME: 'Thiết bị y tế'},
    {CODE: 'FASHION_JEWELERY', NAME: 'Thời trang/Trang sức',},
    {CODE: 'VETERINARY', NAME: 'Thú y'},
    {CODE: 'E_COMMERCE', NAME: 'Thương mại điện tử'},
    {CODE: 'MEDIA_PRESS_ADVERTISING', NAME: 'Truyền thông/Báo chí/Quảng cáo',},
    {CODE: 'AUTOMATION', NAME: 'Tự động hóa'},
    {CODE: 'TRANSPORTATION', NAME: 'Vận tải'},
    {CODE: 'CONSTRUCTION_MATERIALS', NAME: 'Vật liệu xây dựng',},
    {CODE: 'TELECOMMUNICATION', NAME: 'Viễn thông'},
    {CODE: 'OTHER', NAME: 'Khác'},
  ],
  LOGO_COMPANY: [
    {URL: '../../../assets/images/logo_lg.png', NAME: 'LG'},
    {URL: '../../../assets/images/logo_lottemart.webp', NAME: 'Lotte Mart'},
    {URL: '../../../assets/images/logo_nutifood.webp', NAME: 'Nuti Food'},
    {
      URL: '../../../assets/images/logo_techcombank.webp',
      NAME: 'Techcombank',
    },
    {URL: '../../../assets/images/logo_thaco.webp', NAME: 'Thaco'},
    {URL: '../../../assets/images/logo_vettel.webp', NAME: 'Vettel'},
    {URL: '../../../assets/images/logo_vinamilk.webp', NAME: 'Vinamilk'},
    {URL: '../../../assets/images/logo_vinfast.webp', NAME: 'Vinfast'},
    {URL: '../../../assets/images/logo_yamaha.webp', NAME: 'Yamaha'},
  ],
  EDUCATION: [
    {CODE: 'ELEMENTARY_I', NAME: 'Sơ cấp I'},
    {CODE: 'ELEMENTARY_II', NAME: 'Sơ cấp II'},
    {CODE: 'ELEMENTARY_III', NAME: 'Sơ cấp III'},
    {CODE: 'INTERMEDIATE', NAME: 'Trung cấp'},
    {CODE: 'COLLEGE', NAME: 'Cao đẳng'},
    {CODE: 'UNIVERSITY', NAME: 'Đại học'},
    {CODE: 'MASTER', NAME: 'Thạc sĩ'},
    {CODE: 'DOCTORATE', NAME: 'Tiến sĩ'},
  ],
  LANGUAGES: [
    { CODE: 'EN', NAME: 'English' },
    { CODE: 'ZH', NAME: '中文 (Chinese)' },
    { CODE: 'ES', NAME: 'Español (Spanish)' },
    { CODE: 'HI', NAME: 'हिन्दी (Hindi)' },
    { CODE: 'AR', NAME: 'العربية (Arabic)' },
    { CODE: 'PT', NAME: 'Português (Portuguese)' },
    { CODE: 'BN', NAME: 'বাংলা (Bengali)' },
    { CODE: 'RU', NAME: 'Русский (Russian)' },
    { CODE: 'JA', NAME: '日本語 (Japanese)' },
    { CODE: 'PA', NAME: 'ਪੰਜਾਬੀ (Punjabi)' },
    { CODE: 'DE', NAME: 'Deutsch (German)' },
    { CODE: 'JV', NAME: 'Basa Jawa (Javanese)' },
    { CODE: 'KO', NAME: '한국어 (Korean)' },
    { CODE: 'FR', NAME: 'Français (French)' },
    { CODE: 'TE', NAME: 'తెలుగు (Telugu)' },
    { CODE: 'TR', NAME: 'Türkçe (Turkish)' },
    { CODE: 'VI', NAME: 'Tiếng Việt (Vietnamese)' },
    { CODE: 'MR', NAME: 'मराठी (Marathi)' },
    { CODE: 'TA', NAME: 'தமிழ் (Tamil)' },
    { CODE: 'UR', NAME: 'اردو (Urdu)' },
    { CODE: 'FA', NAME: 'فارسی (Persian)' },
    { CODE: 'IT', NAME: 'Italiano (Italian)' },
    { CODE: 'MS', NAME: 'Bahasa Melayu (Malay)' },
    { CODE: 'TH', NAME: 'ภาษาไทย (Thai)' },
    { CODE: 'GU', NAME: 'ગુજરાતી (Gujarati)' },
    { CODE: 'PL', NAME: 'Polski (Polish)' },
    { CODE: 'UK', NAME: 'Українська (Ukrainian)' },
    { CODE: 'RO', NAME: 'Română (Romanian)' },
    { CODE: 'NL', NAME: 'Nederlands (Dutch)' },
    { CODE: 'EL', NAME: 'Ελληνικά (Greek)' }
  ],
  SYSTEM_STATUS: [
    { CODE: 'ACTIVE', NAME: 'active' },
    { CODE: 'IN_ACTIVE', NAME: 'inactive'},
    { CODE: 'LOCK', NAME: 'lock'},
  ],
  SYSTEM_ROLE: [
    { CODE: 'SUPER_ADMIN', NAME: 'super_admin' },
    { CODE: 'ADMIN', NAME: 'admin' },
    { CODE: 'CANDIDATE', NAME: 'candidate' },
    { CODE: 'EMPLOYER', NAME: 'employer' },
  ],
};
